mongo:
  user: non-prod-app
  password: ${MONGO_PASSWORD}
  host: dev-yqjj3.gcp.mongodb.net
  dbPrefix: ${DEV_NAMESPACE}
  url: mongodb+srv://${mongo.user}:${mongo.password}@${mongo.host}/${mongo.db}?retryWrites=true

spring:
  application:
    name: share-it-service
  data:
    mongodb:
      uri: ${mongo.url}

logging:
  config: classpath:logback-cluster.xml
  level:
    net.twill: DEBUG