spring:
  application:
    name: share-it-service
  data:
    mongodb:
      uri: mongodb+srv://non-prod-app:${MONGO_PASSWORD}@dev-yqjj3.gcp.mongodb.net/${DEV_NAMESPACE}_share-it-service

logging:
  level:
    net.twill: DEBUG