apiVersion: v1
kind: Service
metadata:
  name: share-it
  namespace: hackathon
  labels:
    app: share-it
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: http-actuator
      port: 8787
      targetPort: http-actuator
  selector:
    app: share-it
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-it
  namespace: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-it
  template:
    metadata:
      labels:
        app: share-it
    spec:
      containers:
        - image: twill/share-it
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - name: http
              containerPort: 8080
            - name: http-actuator
              containerPort: 8787
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http-actuator
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http-actuator
      nodeSelector:
        node_pool: preemptible
      tolerations:
        - key: preemptible
          operator: Equal
          value: "true"
          effect: NoSchedule